### PR TITLE
g motion handling; gn/gN motion; enabled q

### PR DESCRIPTION
**Pull request by shdwp**
Subject. Q was simply brought back from XVim1.

Now including tests.

### CODE REVIEW

**Comment by pebble8888** [comment]
I have reverted the PR, because of `*`, `n`, `N` command bug.

`n` command search movement doesn't loop.
Please fix this bug and split the PR to gn/gN feature and macro feature each.

**Comment by pebble8888** [comment]
I commited the macro feature only.
Please fix `n` command bug. It's not easy task.

**Comment by shdwp** [comment]
I don't know what are you talking about - I've just cherry-picked the gn/gN commit on top of current develop and *, n and N wraps around as expected, both with and without preceding `g`.

**Comment by pebble8888** [comment]
Sorry, I have confirmed right behavior.
I have reverted again.
Thank you.

**Comment by shdwp** [comment]
No problem, thank you.

**Pull request merged**
